---
- hosts: db
  become: yes
  ignore_errors: yes
  gather_facts: yes
  vars:
    pkg: apache2
  vars_files:
    - vars.yml
  tasks:
    - name: install apache
      apt:
        name: "{{ pkg }}"
        state: present
      when: ansible_processor_nproc == 4
    - name: create a file
      file:
        dest: /var/www/html/index.html
        state: touch
      when: 2 < 0